sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
before_install:
  ## Disable xdebug
  - phpenv config-rm xdebug.ini
  ## Update Composer
  - composer self-update
install:
  ## Install Composer dependencies
  - composer install --no-interaction --prefer-source
  ## Clone libraries
  - hg clone https://bitbucket.org/izi/polib app/libraries/polib -u 1.0.7
  - hg clone https://hg.mozilla.org/l10n/silme app/libraries/silme -u silme-0.8.0
script:
  - vendor/atoum/atoum/bin/atoum -d tests/units/
  - php tests/functional/scripts.php
  - php tests/integrity/source_integrity.php
  - vendor/bin/php-cs-fixer --diff --dry-run -v fix
notifications:
  irc:
    channels:
      - "irc.mozilla.org#l10n-tools"
    on_success: always
    on_failure: always
    use_notice: true
    template:
      - "%{repository} ; %{commit} (%{author}) : %{message} "
      - "Build details: %{build_url} ; changes: %{compare_url}"
matrix:
  fast_finish: true
